//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("projectCUPU1Model", "FK__comment__PlaneID__0519C6AF", "plane", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Project.plane), "comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Project.comment), true)]

#endregion

namespace Project
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class projectCUPU1Entities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new projectCUPU1Entities1 object using the connection string found in the 'projectCUPU1Entities1' section of the application configuration file.
        /// </summary>
        public projectCUPU1Entities1() : base("name=projectCUPU1Entities1", "projectCUPU1Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new projectCUPU1Entities1 object.
        /// </summary>
        public projectCUPU1Entities1(string connectionString) : base(connectionString, "projectCUPU1Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new projectCUPU1Entities1 object.
        /// </summary>
        public projectCUPU1Entities1(EntityConnection connection) : base(connection, "projectCUPU1Entities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<comment> comments
        {
            get
            {
                if ((_comments == null))
                {
                    _comments = base.CreateObjectSet<comment>("comments");
                }
                return _comments;
            }
        }
        private ObjectSet<comment> _comments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<plane> planes
        {
            get
            {
                if ((_planes == null))
                {
                    _planes = base.CreateObjectSet<plane>("planes");
                }
                return _planes;
            }
        }
        private ObjectSet<plane> _planes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the comments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocomments(comment comment)
        {
            base.AddObject("comments", comment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the planes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToplanes(plane plane)
        {
            base.AddObject("planes", plane);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="projectCUPU1Model", Name="comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new comment object.
        /// </summary>
        /// <param name="commentID">Initial value of the CommentID property.</param>
        public static comment Createcomment(global::System.Int32 commentID)
        {
            comment comment = new comment();
            comment.CommentID = commentID;
            return comment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommentID
        {
            get
            {
                return _CommentID;
            }
            set
            {
                if (_CommentID != value)
                {
                    OnCommentIDChanging(value);
                    ReportPropertyChanging("CommentID");
                    _CommentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CommentID");
                    OnCommentIDChanged();
                }
            }
        }
        private global::System.Int32 _CommentID;
        partial void OnCommentIDChanging(global::System.Int32 value);
        partial void OnCommentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PlaneID
        {
            get
            {
                return _PlaneID;
            }
            set
            {
                OnPlaneIDChanging(value);
                ReportPropertyChanging("PlaneID");
                _PlaneID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlaneID");
                OnPlaneIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PlaneID;
        partial void OnPlaneIDChanging(Nullable<global::System.Int32> value);
        partial void OnPlaneIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CommentBody
        {
            get
            {
                return _CommentBody;
            }
            set
            {
                OnCommentBodyChanging(value);
                ReportPropertyChanging("CommentBody");
                _CommentBody = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CommentBody");
                OnCommentBodyChanged();
            }
        }
        private global::System.String _CommentBody;
        partial void OnCommentBodyChanging(global::System.String value);
        partial void OnCommentBodyChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("projectCUPU1Model", "FK__comment__PlaneID__0519C6AF", "plane")]
        public plane plane
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<plane>("projectCUPU1Model.FK__comment__PlaneID__0519C6AF", "plane").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<plane>("projectCUPU1Model.FK__comment__PlaneID__0519C6AF", "plane").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<plane> planeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<plane>("projectCUPU1Model.FK__comment__PlaneID__0519C6AF", "plane");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<plane>("projectCUPU1Model.FK__comment__PlaneID__0519C6AF", "plane", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="projectCUPU1Model", Name="plane")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class plane : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new plane object.
        /// </summary>
        /// <param name="planeID">Initial value of the PlaneID property.</param>
        public static plane Createplane(global::System.Int32 planeID)
        {
            plane plane = new plane();
            plane.PlaneID = planeID;
            return plane;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlaneID
        {
            get
            {
                return _PlaneID;
            }
            set
            {
                if (_PlaneID != value)
                {
                    OnPlaneIDChanging(value);
                    ReportPropertyChanging("PlaneID");
                    _PlaneID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PlaneID");
                    OnPlaneIDChanged();
                }
            }
        }
        private global::System.Int32 _PlaneID;
        partial void OnPlaneIDChanging(global::System.Int32 value);
        partial void OnPlaneIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PlaneName
        {
            get
            {
                return _PlaneName;
            }
            set
            {
                OnPlaneNameChanging(value);
                ReportPropertyChanging("PlaneName");
                _PlaneName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PlaneName");
                OnPlaneNameChanged();
            }
        }
        private global::System.String _PlaneName;
        partial void OnPlaneNameChanging(global::System.String value);
        partial void OnPlaneNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PlaneType
        {
            get
            {
                return _PlaneType;
            }
            set
            {
                OnPlaneTypeChanging(value);
                ReportPropertyChanging("PlaneType");
                _PlaneType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PlaneType");
                OnPlaneTypeChanged();
            }
        }
        private global::System.String _PlaneType;
        partial void OnPlaneTypeChanging(global::System.String value);
        partial void OnPlaneTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EngineType
        {
            get
            {
                return _EngineType;
            }
            set
            {
                OnEngineTypeChanging(value);
                ReportPropertyChanging("EngineType");
                _EngineType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EngineType");
                OnEngineTypeChanged();
            }
        }
        private global::System.String _EngineType;
        partial void OnEngineTypeChanging(global::System.String value);
        partial void OnEngineTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NumberOfEngine
        {
            get
            {
                return _NumberOfEngine;
            }
            set
            {
                OnNumberOfEngineChanging(value);
                ReportPropertyChanging("NumberOfEngine");
                _NumberOfEngine = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumberOfEngine");
                OnNumberOfEngineChanged();
            }
        }
        private Nullable<global::System.Int32> _NumberOfEngine;
        partial void OnNumberOfEngineChanging(Nullable<global::System.Int32> value);
        partial void OnNumberOfEngineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PlaneImage
        {
            get
            {
                return _PlaneImage;
            }
            set
            {
                OnPlaneImageChanging(value);
                ReportPropertyChanging("PlaneImage");
                _PlaneImage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PlaneImage");
                OnPlaneImageChanged();
            }
        }
        private global::System.String _PlaneImage;
        partial void OnPlaneImageChanging(global::System.String value);
        partial void OnPlaneImageChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("projectCUPU1Model", "FK__comment__PlaneID__0519C6AF", "comment")]
        public EntityCollection<comment> comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<comment>("projectCUPU1Model.FK__comment__PlaneID__0519C6AF", "comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<comment>("projectCUPU1Model.FK__comment__PlaneID__0519C6AF", "comment", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
